package com.neueda.leap;

import com.neueda.leap.entity.Account;
import com.neueda.leap.entity.Client;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.time.LocalDate;
import static org.junit.jupiter.api.Assertions.*;

public class ClientTest {

    private Client client;

    @BeforeEach
    void setUp() {
        // ID is auto-generated by the domain model.
        client = new Client("John Doe", LocalDate.of(1990, 5, 15));
    }

    // BR-01: Client Registration
    @Test
    void testClientCreationWithValidData() {
        assertNotNull(client);
        assertTrue(client.getId() > 0);
        assertEquals("John Doe", client.getName()); //getName() should be split for first/last name
        assertEquals(LocalDate.of(1990, 5, 15), client.getBirthDate());
    }

    @Test
    void testClientRegistrationRequiresName() {
        assertThrows(IllegalArgumentException.class,
                () -> new Client(null, LocalDate.of(1990, 5, 15)));
    }

    @Test
    void testClientRegistrationRequiresBirthDate() {
        assertThrows(IllegalArgumentException.class,
                () -> new Client("John Doe", null));
    }

    @Test
    void testClientCannotHaveFutureAsBirthDate() {
        assertThrows(IllegalArgumentException.class,
                () -> new Client("John Doe", LocalDate.now().plusYears(1)));
    }

    // BR-02: Clients can only access their own data
    @Test
    void testClientIdMustBeUnique() {
        Client client2 = new Client("Jane Smith", LocalDate.of(1988, 3, 20));
        assertNotEquals(client.getId(), client2.getId());
    }

    @Test
    void testClientCanViewOwnAccounts() {
        Account account1 = new Account(101, "Trading", client.getId());
        Account account2 = new Account(102, "Cash", client.getId());

        client.addAccount(account1);
        client.addAccount(account2);

        assertEquals(2, client.getAccounts().size());
        assertTrue(client.getAccounts().stream()
            .allMatch(a -> a.getClientId() == client.getId()));
    }

}